### ISSUE TITLE
404 thrown on invisible or hidden location, event on back office

### ISSUE THREAD

**Issue by bOnepain** [Novactive/NovaeZExtraBundle#33]
Hello,

I'm not sure but it seems it's a issue : when trying to display an invisible or hidden location on the backoffice, the \Novactive\Bundle\eZExtraBundle\EventListener\PreContentViewListener throws a 404
```
if ($location->invisible == 1 or $location->hidden == 1) {
    throw new NotFoundHttpException("Page not found");
}
```

I understand that content shouldn't be displayed on the frontend, but it should be possible to edit on the back office.

Thanks in advance

**Comment by Plopix** [comment]
Do you have the last version of the bundle? @bOnepain ?

https://github.com/Novactive/NovaeZExtraBundle/commit/94d0cf97392a747262c439ad0d25176dfe4f42da

**Comment by bOnepain** [comment]
Yes thank you, that was it ! It was an outdated version. Once updated, works fine !
